### ISSUE TITLE
ImportError: cannot import name '_from_URL_fileopen' from 'weblogo'

### ISSUE THREAD

**Issue by feedmewifi** [WebLogo/weblogo#112]
I run:
`weblogo -D table -o test.svg -F svg -A rna --upload https://attract.cnic.es/attract/static/matrix/s79.txt`

I get:
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/weblogo", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weblogo/_cli.py", line 78, in main
    data = _build_logodata(opts)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weblogo/_cli.py", line 150, in _build_logodata
    from . import _from_URL_fileopen
ImportError: cannot import name '_from_URL_fileopen' from 'weblogo' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weblogo/__init__.py)
`

Running on Python 3.8.2

Installed weblogo via:
`pip install weblogo`

**Comment by feedmewifi** [comment]
If I try downloading the PWM and inputting it myself:

`python3 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weblogo/_cli.py -D table -o test.svg -F svg -A rna -fin test_PWM.txt `

I get:

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/weblogo/_cli.py", line 49, in <module>
    from . import seq_io
ImportError: attempted relative import with no known parent package`

**Comment by gecrooks** [comment]
Thanks. The --upload option should be fixed in release 3.7.8. (Although your data doesn't seem to be in a form WebLogo can understand. But that's a separate issue.)

   pip install -U weblogo
