### ISSUE TITLE
Ghost Script For creating PDF file

### ISSUE THREAD

**Issue by littlekoreanboy** [WebLogo/weblogo#167]
Hello! 

I am having issues generating a PDF file for my weblogo. This is my command:

weblogo -f muscled_AaegyptiLVPWY_7tm_1_domain.fasta -D fasta -o Test -F pdf

And this is the issue:

Traceback (most recent call last):
  File "/home/joelshin/miniconda3/envs/GPCR/bin/weblogo", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/joelshin/miniconda3/envs/GPCR/lib/python3.11/site-packages/weblogo/_cli.py", line 94, in main
    logo = formatter(data, format)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joelshin/miniconda3/envs/GPCR/lib/python3.11/site-packages/weblogo/logo_formatter.py", line 50, in pdf_formatter
    return gs.convert("pdf", eps, logoformat.logo_width, logoformat.logo_height)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joelshin/miniconda3/envs/GPCR/lib/python3.11/site-packages/weblogo/logo_formatter.py", line 413, in convert
    raise RuntimeError(error_msg)
RuntimeError: Unrecoverable error : Ghostscript conversion failed (Invalid postscript?). /usr/bin/gs -sDEVICE=pdfwrite -dPDFSETTINGS=/printer -sstdout=%stderr -dColorConversionStrategy=/LeaveColorUnchanged -sOutputFile=- -dDEVICEWIDTHPOINTS=470 -dDEVICEHEIGHTPOINTS=2110 -dSAFER -dNOPAUSE -r300 -
Return code: 1
b"GPL Ghostscript 9.55.0 (2021-09-27)\nCopyright (C) 2021 Artifex Software, Inc.  All rights reserved.\nThis software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:\nsee the file COPYING for details.\nQuerying operating system for font files...\nCan't find (or can't open) font file /usr/share/ghostscript/9.55.0/Resource/Font//usr/sh.\nCan't find (or can't open) font file ArialMT.\nDidn't find this font on the system!\nSubstituting font Helvetica for ArialMT.\nLoading NimbusSans-Regular font from /usr/share/ghostscript/9.55.0/Resource/Font/NimbusSans-Regular... 5143956 3625799 4050132 2693688 2 done.\nLoading NimbusMonoPS-Regular font from /usr/share/ghostscript/9.55.0/Resource/Font/NimbusMonoPS-Regular... 5230268 3860574 4110732 2734161 2 done.\nError: /unknownerror in --.FAPIBuildChar--\nOperand stack:\n   --dict:17/19(ro)(G)--   73\nExecution stack:\n   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1990   1   3   %oparray_pop   1989   1   3   %oparray_pop   1988   1   3   %oparray_pop   --nostringval--   1977   1   3   %oparray_pop   1833   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   --nostringval--   --nostringval--   %finish_show   --nostringval--   --nostringval--   11   3   0   --nostringval--   (gs_show_enum)   %op_show_continue\nDictionary stack:\n   --dict:768/1123(ro)(G)--   --dict:0/20(G)--   --dict:194/200(L)--\nCurrent allocation mode is local\nGPL Ghostscript 9.55.0: Unrecoverable error, exit code 1\n"

Thank you in advance!

**Comment by SanityTree** [comment]
I know this was posted over a year ago but I just had the same issue and I just had to set the ghost script path to my computer's font files. In my case I typed this into my Anaconda prompt:

set GS_FONTPATH=C:\Windows\Fonts

I think this is the default Path for fonts on windows. This allowed me to generate pdf files, but you have to repeat it every time your open a new window. There is probably a permanent solution but I do not know how currently.
