### ISSUE TITLE
moremath error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [WebLogo/weblogo#41]
```
I'm using WebLogo with 8 similar input files; 7 give the expected output (I 
know what the base composition is, I'm just using WebLogo to visualize) but the 
final file gives this error:

/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/web
logolib/logomath.py:333: RuntimeWarning: divide by zero encountered in 
double_scalars
  x2 = x1 - v1*(x1-x0)/(v1-v0)
/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/cor
ebio/moremath.py:417: RuntimeWarning: invalid value encountered in 
double_scalars
  term = d * c
Traceback (most recent call last):
  File "/Users/josmundson/anaconda/bin/weblogo", line 5, in <module>
    pkg_resources.run_script('weblogo==3.4', 'weblogo')
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/setuptools-2.2-py2.7.egg/pkg_resources.py", line 488, in run_script
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/setuptools-2.2-py2.7.egg/pkg_resources.py", line 1354, in run_script
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/EGG-INFO/scripts/weblogo", line 71, in <module>
    weblogolib._cli.main()
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/_cli.py", line 80, in main
    data = _build_logodata(opts)
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/_cli.py", line 193, in _build_logodata
    data = LogoData.from_seqs(seqs, prior)
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/__init__.py", line 1149, in from_seqs
    return cls.from_counts(seqs.alphabet, counts, prior)
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/__init__.py", line 1118, in from_counts
    posterior.interval_relative_entropy(prior/sum(prior), 0.95) 
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/logomath.py", line 243, in interval_relative_entropy
    low_limit = g.inverse_cdf( (1.-frac)/2.)
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/logomath.py", line 297, in inverse_cdf
    return exp(find_root(  rootof, log(self.mean()) ) )
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/logomath.py", line 390, in find_root
    return secant(f, x, tolerance, max_iterations)
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/logomath.py", line 338, in secant
    v1 = f(x1)
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/logomath.py", line 295, in rootof
    return self.cdf(exp(x)) - p
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/weblogolib/logomath.py", line 291, in cdf
    return 1.0-normalized_incomplete_gamma(self.alpha, self.beta*x)
  File "/Users/josmundson/anaconda/lib/python2.7/site-packages/weblogo-3.4-py2.7.egg/corebio/moremath.py", line 422, in normalized_incomplete_gamma
    "Failed to converge after %d iterations." % (maxiter) )
RuntimeError: Failed to converge after 100 iterations.

What version of the product are you using? On what operating system?

WebLogo v3.4
Python v2.7
MacOsX 10.8.4

Please provide any additional information below.

```

Original issue reported on code.google.com by `j...@nyu.edu` on 19 May 2015 at 4:51

**Comment by gecrooks** [comment]
I think I've fixed this issue. But to be sure, could you please provide an input file that triggers this bug.
