### ISSUE TITLE
How can i make new alphabet?

### ISSUE THREAD

**Issue by MarcGrad** [WebLogo/weblogo#73]

**Comment by MarcGrad** [comment]
I need selenocysteine in logo. But reduced_protein_alphabet don't work. I dont understand docstring about weblogolib.Alphabet.__new__(). 
```
weblogolib.Alphabet.__new__('ACDEFGHIKLMNPQRSTVUWY', zip('acdefghiklmnpqrstvuwy','ACDEFGHIKLMNPQRSTVUWY'))
Traceback (most recent call last):

  File "<ipython-input-114-1c1286ba9c1d>", line 1, in <module>
    weblogolib.Alphabet.__new__('ACDEFGHIKLMNPQRSTVUWY', zip('acdefghiklmnpqrstvuwy','ACDEFGHIKLMNPQRSTVUWY'))

  File "/home/marcin/.conda/envs/my_root/lib/python3.6/site-packages/corebio/seq.py", line 185, in __new__
    self = object.__new__(cls)

TypeError: object.__new__(X): X is not a type object (str)
```

**Comment by gecrooks** [comment]
You don't need to call __new__() directly. Just instantiate a class as usual. 

weblogolib.Alphabet('ACDEFGHIKLMNPQRSTVUWY', zip('acdefghiklmnpqrstvuwy','ACDEFGHIKLMNPQRSTVUWY'))
