### ISSUE TITLE
Install fails if numpy is not already installed

### ISSUE THREAD

**Issue by ecederstrand** [WebLogo/weblogo#76]
I just tried installing weblogo in an empty virtualenv. This fails because `setup.py` does `from weblogolib import __version__`, and `weblogolib/__init__.py` imports `numpy`, but `numpy` is not yet installed.

```bash
$ virtualenv -p python3 foo
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in foo/bin/python3
Also creating executable in foo/bin/python
Installing setuptools, pip...done.
$ source foo/bin/activate
$ pip3 install weblogo
Collecting weblogo
  Downloading http://pypi.python.org/packages/86/32/bb72ad056f186e68a8518ca34eef85494dd564238945c6f29522e463a57e/weblogo-3.5.0.tar.gz (434kB)
    100% |████████████████████████████████| 440kB 2.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jnjhkqf8/weblogo/setup.py", line 12, in <module>
        from weblogolib import __version__
      File "/tmp/pip-build-jnjhkqf8/weblogo/weblogolib/__init__.py", line 102, in <module>
        from numpy import array, asarray, float64, ones, zeros, any, int32, all, shape
    ImportError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jnjhkqf8/weblogo/
```

I could fix this by just installing `numpy` first, but that doesn't work if I want to create my virtualenv using a `requirements.txt` file.

**Comment by gecrooks** [comment]
Fixed in commit b7a4dde
